Move the features (Patterns - Catalog functions, SB Channel, Liveview Metric Store, Analytics Catalog Functions, MQTT Channel, Kafka Streams) to github.
TIBCOSoftware/be-contribution pull request #115
Opened 2023-06-22 15:59 UTC by tyogeshp-tibco

2023-06-23 12:24 UTC, rakulkar-tibco commented on channel/mqtt/pom.xml
> +        <mqtt.version></mqtt.version>
declare and use mqtt version

2023-06-23 19:11 UTC, rakulkar-tibco requested changes

2023-06-23 19:43 UTC, rakulkar-tibco requested changes

2023-06-23 19:43 UTC, rakulkar-tibco commented on channel/sb/pom.xml
> +			<groupId>com.tibco.xml</groupId>
which Mvn repo it is referring to? you need to specify the system path.

2023-06-23 19:43 UTC, rakulkar-tibco commented on channel/sb/pom.xml
> +			<groupId>com.tibco.xml</groupId>
same as above. and for all tibco dependencies.

2023-06-23 19:43 UTC, rakulkar-tibco commented on channel/sb/pom.xml
> +			<groupId>com.tibco.as</groupId>
does it have dependency on AS?

2023-06-23 19:43 UTC, rakulkar-tibco commented on channel/sb/pom.xml
> +			<artifactId>as-agent</artifactId>
same as above

2023-06-23 19:43 UTC, rakulkar-tibco commented on channel/sb/pom.xml
> +		<!--dependency>
cleanup this. 
Remove unwanted dependencies in all pom.xmls

2023-06-23 19:43 UTC, rakulkar-tibco commented on channel/kafka-streams/src/main/java/com/tibco/cep/driver/kafkastreams/KafkaDriver.java
> +public class KafkaDriver extends BaseDriver {
Why KafkaDriver ? Use / copy only required classes from kafka.

2023-06-23 19:43 UTC, rakulkar-tibco commented on metric/liveview/pom.xml
> +		<artifactId>sbclient</artifactId>
You need to use System path which will refer to BE installation.

2023-06-23 19:43 UTC, rakulkar-tibco commented on metric/liveview/pom.xml
> +		<groupId>com.tibco.str</groupId>
same as  above for all tibco dependecies.

2023-06-23 19:43 UTC, rakulkar-tibco commented on metric/liveview/pom.xml
> +		<groupId>com.tibco.str</groupId>
clean this.

2023-06-23 19:43 UTC, rakulkar-tibco commented on catalog/analytics-catalog-fn/pom.xml
> +			<groupId>com.tibco</groupId>
use system which refers to BE installation.

2023-06-23 19:43 UTC, rakulkar-tibco commented on catalog/analytics-catalog-fn/pom.xml
> +		<!--dependency>
remove commented dependencies

2023-06-23 19:43 UTC, rakulkar-tibco commented on catalog/analytics-catalog-fn/pom.xml
> +			<groupId>com.tibco.tra</groupId>
For all tibco dependecies use system path referring to BE home,as they are not part of mvn.

2023-06-23 19:43 UTC, rakulkar-tibco commented on catalog/analytics-catalog-fn/pom.xml
> +			<groupId>com.tibco.tibcoxml</groupId>
For all eclipse dependencies reuse dependenies from parent pom.xml

2023-06-23 19:43 UTC, rakulkar-tibco commented on catalog/pattern-catalog-fn/pom.xml
> +			<groupId>com.tibco.tibcoxml</groupId>
Reuse dependencies in parent pom.xml

2023-06-28 02:46 UTC, tyogeshp-tibco commented on channel/mqtt/pom.xml
> +			<artifactId>jms</artifactId>
not dependent, removing from pom.

2023-06-28 02:48 UTC, tyogeshp-tibco commented on channel/kafka-streams/pom.xml
> +			<artifactId>tibftl-kafka-avro</artifactId>
Included in kafka's classpath.

2023-06-28 02:48 UTC, tyogeshp-tibco commented on channel/kafka-streams/pom.xml
> +			<artifactId>kafka-schema-registry</artifactId>
not required, removing.

2023-06-28 02:52 UTC, tyogeshp-tibco commented on channel/kafka-streams/pom.xml
> +			<artifactId>avro</artifactId>
removing avro, mvn clean is showing errors in building the jar.

2023-06-28 02:52 UTC, tyogeshp-tibco commented on channel/kafka-streams/pom.xml
> +			<artifactId>kafka-avro-serializer</artifactId>
included in kafka's classpath

2023-07-03 09:23 UTC, rakulkar-tibco requested changes

2023-07-04 12:09 UTC, rakulkar-tibco reviewed
Also move the examples to be-samples repo

2023-07-04 12:57 UTC, tyogeshp-tibco commented on channel/sb/pom.xml
> +			<systemPath>${sb.home}/sb-java-tools.jar</systemPath>
the property contains the path till ${sb.home}/lib/.

2023-07-07 08:06 UTC, merged