Implementation of MongoDB store using custom store API
TIBCOSoftware/be-contribution pull request #42
Opened 2021-06-23 12:04 UTC by jgirase

This enhances the support for document oriented database mongoDB with BE. It has been implemented using custom store APIs.
Supported operations are as below,
- Insert
- Update
- Delete
- Retrieval

In addition to that, support for aggregates is also been added which covers basic functions like count/sum/min/max/avg

2021-07-16 20:12 UTC, vpatil-tibco requested changes
@jgirase  Good starting point. Shared few initial comments.

Also i am assuming you have validated this with a latest 6.1.1 build.

2021-07-16 20:12 UTC, vpatil-tibco commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +	private static ThreadLocal<Boolean> isTxExecution = new ThreadLocal<Boolean>() {
Use inline shortcut "ThreadLocal.withInitial(()->false)"

2021-07-16 20:12 UTC, vpatil-tibco commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +					if (ttl > 0) {
Can you share more details on what we are doing here? I don't quite get what is index got to do with having a ttl? Why are we deleting/creating an index?

2021-07-16 20:12 UTC, vpatil-tibco commented on store/mongoDB/src/main/resources/store.xml
> +	      	<property name="isSRV" displayName="Is SRV Enabled URI" type="Boolean" default="false" />
Same as above we can skip this one.

2021-07-19 06:17 UTC, jgirase commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +					if (ttl > 0) {
TTL indexes are special indexes that MongoDB can use to automatically remove documents from a collection after a certain amount of time.So to handle BE TTL feature, I have used these indexes based on what values are mentioned in cdd. Once the index is created we can not really change its value so to handle this I have deleted and recreated indexes whenever required. In addition to that, index creation will vary as per fields time_created_ and time_last_modified_.
For validating basic test cases BE 6.1.1 is used only.

2021-07-19 21:28 UTC, vpatil-tibco commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +					if (ttl > 0) {
Ok, but why to do this during every write call. Can't we simply do this when a collection is created by adding this index with appropriate ttl value on 'timeCreated' field?

2021-07-20 13:41 UTC, jgirase commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +					if (ttl > 0) {
Collection is created when the first write operation in invoked in write() function only as we are generating schema at runtime only. so I am not sure where can we put this code apart from write() method.

2021-07-21 10:57 UTC, jgirase commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +		Boolean isSRV = Boolean.parseBoolean(
Separate fields like 'Is SRV'/'Options' are removed so user can mention the same in URI itself. User/password are optional and password can not be in plain text so these fields are present in cdd along with database. The authentication database for mongoDB users can be mentioned in URI only in case users are created in separate database except admin(default one). Otherwise optional 'options' can also be used as a part of URI.

2021-07-21 10:58 UTC, jgirase commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +	private static ThreadLocal<Boolean> isTxExecution = new ThreadLocal<Boolean>() {
This has been added

2021-07-21 10:59 UTC, jgirase commented on store/mongoDB/src/main/resources/store.xml
> +	      	<property name="isSRV" displayName="Is SRV Enabled URI" type="Boolean" default="false" />
This is also addressed

2021-07-21 15:31 UTC, vpatil-tibco commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +		{
Minor thing, but for consistent code readablilty, make sure to follow a single coding format.
E.g. 
if (condition) {
} else (another Condition) {
}
if the generally followed pattern.

2021-07-21 15:48 UTC, vpatil-tibco commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +		} catch (Exception e) {
Handle/throw the exception.

2021-07-21 16:10 UTC, vpatil-tibco commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +					if (ttl > 0) {
So we are not generating an upfront schema like other stores. Here we are creating schema on the fly. Now coming to the logic, shouldn't it be simply be,
if (column == TIME_CREATED)
     if (! indexExits(TIME_CREATED))
        createIndex(TIME_CREATED, ttl);

Not sure why do we need to check TIME_MODIFIED and/or drop and recreate?

2021-07-22 11:44 UTC, jgirase commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/AggregatesBuilder.java
> +			if(groupByColSet.isEmpty())
This has been addressed

2021-07-22 11:45 UTC, jgirase commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +		{
Done some changes around if/else. Please take a look

2021-07-22 11:46 UTC, jgirase commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +		} catch (Exception e) {
Added code for throwing exception

2021-07-22 12:49 UTC, jgirase commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +					if (ttl > 0) {
Correct me if my understanding is wrong. Tried to handle a case where , concept is having ttl =120 sec. It has been created at time time_created and modified after some time time_modified. Then concept will expire at time_modified+ ttl so if concept is updated new ttl index will be created using time_modified value. In this case the previous index time_created has to be deleted otherwise document from collection will be deleted using that index only. Even if concept is modified multiple times then ttl index will be created with latest modified value.
Let me know if this is not the expected behaviour otherwise I will update the code to have index based on time_created only.

2021-07-22 15:55 UTC, vpatil-tibco commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/AggregatesBuilder.java
> +	public static void buildAggregationPipeline(BsonField aggfunction,List<String> groupByColSet,String aggCol,List<Bson> aggegationpipeline)
I dont think you need to pass "aggCol", you can get it the necessary details off aggfunction, it has getName() and getValue() methods.

2021-07-22 15:57 UTC, vpatil-tibco commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/AggregatesBuilder.java
> +	{
Use consistent formatting, like use the open curly braces right after the function instead on a linefeed. E.g.

public class Employee {
}

public void getData() {
}

if (condition) {
}

2021-07-22 15:58 UTC, vpatil-tibco commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +		closeConnection();
Check for transaction.

2021-07-22 15:59 UTC, vpatil-tibco commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +		{
Not all cases and files are covered. You have to do it across for consistency.

2021-07-22 16:02 UTC, vpatil-tibco commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +					if (ttl > 0) {
Yes that is the behavior with caches but can you check if same behavior applies to AS4/Cassandra.

2021-07-22 16:02 UTC, vpatil-tibco commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +			e.printStackTrace();
Add to the logs. Avoid pushing to sys out.

2021-07-22 16:04 UTC, vpatil-tibco commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/AggregatesBuilder.java
> +			if(groupByColSet.isEmpty())
Yes, i see that, but there is a follow up comment.

2021-07-23 11:01 UTC, jgirase commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +			e.printStackTrace();
This has been addressed

2021-07-23 11:01 UTC, jgirase commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/AggregatesBuilder.java
> +	public static void buildAggregationPipeline(BsonField aggfunction,List<String> groupByColSet,String aggCol,List<Bson> aggegationpipeline)
Changes are done

2021-07-23 11:07 UTC, jgirase commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/AggregatesBuilder.java
> +	{
Done

2021-07-23 16:06 UTC, vpatil-tibco commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/AggregatesBuilder.java
> +		for(String field:groupByColSet){
If you are using Eclipse for coding, use the code formatter. Since some places its done correctly some places spaces are missing.
Like this one there is not space after 'for' and no space before '{'

2021-07-26 12:36 UTC, jgirase commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +					if (ttl > 0) {
Yes its same for AS4/Cassandra

2021-07-27 10:41 UTC, jgirase commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +		try {
Added the transaction check

2021-07-27 10:41 UTC, jgirase commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +		try {
Added the transaction check otherwise throws exception

2021-07-27 10:42 UTC, jgirase commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +		{
Did formatting using eclipse commands

2021-07-27 10:42 UTC, jgirase commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +		closeConnection();
Transaction check is performed

2021-07-27 10:43 UTC, jgirase commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/AggregatesBuilder.java
> +		for(String field:groupByColSet){
Used eclipse formatting and checked in all files

2021-07-27 16:51 UTC, vpatil-tibco commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +			if (clientsession.get() != null && clientsession.get().hasActiveTransaction())
For transaction check, either use "isTxExecution" or "clientSession.get().hasActiveTransaction()". I'd prefer to use the native api instead a locally maintained variable.

2021-07-27 16:55 UTC, vpatil-tibco commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +	private boolean checkIfIndexExist(MongoCollection<Document> collection, String indexName) {
Don't need this method. Can be removed. Just use "getIndexName"

2021-07-27 16:59 UTC, vpatil-tibco commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +			if (indexdoc.get("name").toString().equalsIgnoreCase(columnName + "_1")
First retrieve the indexName, rather than extracting every single time. And add a defensive check.
for () {
String indexName = indexDoc.get("name").toString();
if (indexName != null && (indexName.equalsIgnoreCase(columnName+"_1") || indexName.equalsIgnoreCase(columnName+"-1")) return indexName;

2021-07-27 17:42 UTC, vpatil-tibco commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +								if (!checkIfIndexExist(collection,
Simplify this logic,
if (update) {
String indexName = getIndexName(collection, MongoDBConstants.PROPERTY_KEY_MONGODB_TIME_MODIFIED);
if (indexName == null) indexName = getIndexName(collection, MongoDBConstants.PROPERTY_KEY_MONGODB_TIME_CREATED);
if (indexName != null) { // Shouldn't be 'null' at this point
collection.dropIndex(indexName);
collection.createIndex(
								Indexes.ascending(MongoDBConstants.PROPERTY_KEY_MONGODB_TIME_MODIFIED),
											new IndexOptions().expireAfter(Long.valueOf(ttl), TimeUnit.SECONDS));
}

} 
Same changes apply for else-if case as well.

2021-07-27 17:42 UTC, vpatil-tibco commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +						} else {
I am not sure what this case is for.

2021-07-29 09:41 UTC, jgirase commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +			if (clientsession.get() != null && clientsession.get().hasActiveTransaction())
Used "isTxExecution"  for transaction check now. Let me know for more changes

2021-07-29 09:42 UTC, jgirase commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +	private boolean checkIfIndexExist(MongoCollection<Document> collection, String indexName) {
Removed it

2021-07-29 09:43 UTC, jgirase commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +			if (indexdoc.get("name").toString().equalsIgnoreCase(columnName + "_1")
Changes are completed

2021-07-29 09:43 UTC, jgirase commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +								if (!checkIfIndexExist(collection,
This has also been updated

2021-07-29 09:48 UTC, jgirase commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +						} else {
The last else case is for the scenario when TTL is set for the concept then index will be created. However if user removed TTL value or set it to -1  and run the tests again then index will still exist and documents will expire so in that case if ttl is less than 0 and if any index already exist then it can be dropped. Its kind of cleaning up the indexes in case they are not required.

2021-07-29 15:02 UTC, vpatil-tibco commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +			if (clientsession.get() != null && clientsession.get().hasActiveTransaction())
Wouldn't it be the same thing? 'clientSession.get().hasActiveTransaction()' tells you if there is an active transaction available.

2021-07-29 15:06 UTC, vpatil-tibco commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +						} else {
Ahh ok right i.e. for no TTL. I got mixed up with indexes and it seemed to be an else case for (isUpdate) with else if in picture.

2021-07-30 13:28 UTC, jgirase commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +			if (clientsession.get() != null && clientsession.get().hasActiveTransaction())
Yes its about checking transaction only. Initially I used method clientSession.get().hasActiveTransaction() then replaced it with isTxExecution(). So I am not sure what is expected here can you please elaborate.

2021-07-30 21:19 UTC, vpatil-tibco commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +			if (clientsession.get() != null && clientsession.get().hasActiveTransaction())
You haven't mentioned the reason to use 'isTxExecution' flag in some places. If there is no specific reason to use "isTxExecution" instead of "clientSession.get().hasActiveTransaction()", then i prefer you use "clientSession.get().hasActiveTransaction()" at all places and remove "isTxExecution" altogether.

2021-08-04 10:37 UTC, jgirase commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +			if (clientsession.get() != null && clientsession.get().hasActiveTransaction())
Sorry my bad I was considering only two functions for reference. Removed "isTxExecution" and used clientSession.get(). apis now for all transaction related functions.

2021-08-04 17:42 UTC, vpatil-tibco commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +			if (clientsession.get() != null && clientsession.get().hasActiveTransaction() == true)
You don't need to check equality here, instead of "clientsession.get().hasActiveTransaction() == true" simply use "clientsession.get().hasActiveTransaction()"

Also best if this is moved to method that way you can call that method from all places you need,
private boolean hasActiveTransaction() {
       return (clientsession.get() != null && clientsession.get().hasActiveTransaction());
}

2021-08-04 17:43 UTC, vpatil-tibco commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +		if (clientsession.get() != null) {
Missing hasActiveTransaction check. You can use the same method call here as well.

2021-08-06 11:52 UTC, jgirase commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +			if (clientsession.get() != null && clientsession.get().hasActiveTransaction() == true)
Separate method is added now to validate active transaction as mentioned above

2021-08-06 11:56 UTC, jgirase commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +		if (clientsession.get() != null) {
In endTransaction call, clientsession.get().hasActiveTransaction() returns false so it throws exception if validation is added for clientsession.get().hasActiveTransaction() method.
Actually after committing the transaction in commitTransaction() method , clientsession.get().hasActiveTransaction() returns false so cant use it in endTransaction().

2021-08-11 17:31 UTC, vpatil-tibco commented on store/mongoDB/src/main/java/com/tibco/be/mongoDB/MongoDBStoreProvider.java
> +		if (clientsession.get() != null) {
Ok, that makes sense. Commit closes the transaction, so end transaction simply closes it.

2021-08-11 17:34 UTC, vpatil-tibco approved these changes
We are good to merge now.

2021-08-11 17:34 UTC, merged