Provide support for Container Credentials for SQS Channel #43
TIBCOSoftware/be-contribution pull request #44
Opened 2021-08-10 10:42 UTC by shekhar-dev-tibco

Provide support for Container Credentials for SQS Channel #43

2021-08-13 02:59 UTC, vpatil-tibco requested changes
Most of it looks ok. Some minor comments. I don't see any add/update to unit test for this. Can you include that too.

2021-08-13 02:59 UTC, vpatil-tibco commented on channel/aws-sqs/src/main/java/com/tibco/be/custom/channel/aws/sqs/SqsListener.java
> +            logger.log(Level.DEBUG,"Using Contaimer Context");
Typo

2021-08-13 02:59 UTC, vpatil-tibco commented on channel/aws-sqs/src/main/java/com/tibco/be/custom/channel/aws/sqs/containercredentials/ContainerContext.java
> +package com.tibco.be.custom.channel.aws.sqs.containercredentials;
Include header with necessary documentation.

2021-08-18 06:00 UTC, shekhar-dev-tibco commented
Incorporated review comments. Testing for the same is out of scope for dev, as it involves ECS setup with required variables for the same.

2021-08-18 15:10 UTC, vpatil-tibco commented
For tests we use LocalStackContainer which mocks all AWS resources, so you should be able to use that to mock this option as well.

2021-08-19 09:16 UTC, shekhar-dev-tibco commented
https://github.com/localstack/localstack
ECS is supported in pro version

2021-08-19 17:14 UTC, merged